// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using NetCore.Fundamentals.Client.Web.Data.Entities;
using System;

namespace NetCore.Fundamentals.Client.Web.Data.Context
{
    public class UsuarioConfiguration : IEntityTypeConfiguration<Usuario>
    {
        public void Configure(EntityTypeBuilder<Usuario> entity)
        {
            entity.ToTable("Usuario");

            entity.Property(e => e.ApellidoMaterno)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.ApellidoPaterno)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.Clave)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
                        
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.NombreUsuario)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
        }
    }
}
