// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCore.Fundamentals.Client.Web.Data.Context;

namespace NetCore.Fundamentals.Client.Web.Migrations
{
    [DbContext(typeof(GalaxyContext))]
    [Migration("20201105022854_RemoveCustomField")]
    partial class RemoveCustomField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetCore.Fundamentals.Client.Web.Data.Entities.Comentario", b =>
                {
                    b.Property<int>("ComentarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contenido")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdActualizacion")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdCreacion")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdPropietario")
                        .HasColumnType("int");

                    b.HasKey("ComentarioId");

                    b.HasIndex("PostId");

                    b.HasIndex("UsuarioIdActualizacion");

                    b.HasIndex("UsuarioIdCreacion");

                    b.HasIndex("UsuarioIdPropietario");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("NetCore.Fundamentals.Client.Web.Data.Entities.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contenido")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<int>("UsuarioIdActualizacion")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdCreacion")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIdPropietario")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.HasIndex("UsuarioIdActualizacion");

                    b.HasIndex("UsuarioIdCreacion");

                    b.HasIndex("UsuarioIdPropietario");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("NetCore.Fundamentals.Client.Web.Data.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("NetCore.Fundamentals.Client.Web.Data.Entities.Comentario", b =>
                {
                    b.HasOne("NetCore.Fundamentals.Client.Web.Data.Entities.Post", "Post")
                        .WithMany("Comentarios")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_ComentarioPost")
                        .IsRequired();

                    b.HasOne("NetCore.Fundamentals.Client.Web.Data.Entities.Usuario", "UsuarioIdActualizacionNavigation")
                        .WithMany("ComentarioUsuarioIdActualizacionNavigations")
                        .HasForeignKey("UsuarioIdActualizacion")
                        .HasConstraintName("FK_ComentarioUsuarioActualizacion")
                        .IsRequired();

                    b.HasOne("NetCore.Fundamentals.Client.Web.Data.Entities.Usuario", "UsuarioIdCreacionNavigation")
                        .WithMany("ComentarioUsuarioIdCreacionNavigations")
                        .HasForeignKey("UsuarioIdCreacion")
                        .HasConstraintName("FK_ComentarioUsuarioCreacion")
                        .IsRequired();

                    b.HasOne("NetCore.Fundamentals.Client.Web.Data.Entities.Usuario", "UsuarioIdPropietarioNavigation")
                        .WithMany("ComentarioUsuarioIdPropietarioNavigations")
                        .HasForeignKey("UsuarioIdPropietario")
                        .HasConstraintName("FK_ComentarioUsuarioPropietario")
                        .IsRequired();
                });

            modelBuilder.Entity("NetCore.Fundamentals.Client.Web.Data.Entities.Post", b =>
                {
                    b.HasOne("NetCore.Fundamentals.Client.Web.Data.Entities.Usuario", "UsuarioIdActualizacionNavigation")
                        .WithMany("PostUsuarioIdActualizacionNavigations")
                        .HasForeignKey("UsuarioIdActualizacion")
                        .HasConstraintName("FK_PostUsuarioActualizacion")
                        .IsRequired();

                    b.HasOne("NetCore.Fundamentals.Client.Web.Data.Entities.Usuario", "UsuarioIdCreacionNavigation")
                        .WithMany("PostUsuarioIdCreacionNavigations")
                        .HasForeignKey("UsuarioIdCreacion")
                        .HasConstraintName("FK_PostUsuarioCreacion")
                        .IsRequired();

                    b.HasOne("NetCore.Fundamentals.Client.Web.Data.Entities.Usuario", "UsuarioIdPropietarioNavigation")
                        .WithMany("PostUsuarioIdPropietarioNavigations")
                        .HasForeignKey("UsuarioIdPropietario")
                        .HasConstraintName("FK_PostUsuarioPropietario")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
